[package]
name = "bitmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2.1"
radium = "1.0.0"

[dev-dependencies]
itertools = "0.11.0"
